controller_manager:
  ros__parameters:
    update_rate: 500

    dog_controller:
      type: dog_controller/DogController

    dog_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

  dog_controller:
     ros__parameters:
       joints:
         - lf_joint1
         - lf_joint2
         - lf_joint3
         - rf_joint1
         - rf_joint2
         - rf_joint3
         - lb_joint1
         - lb_joint2
         - lb_joint3
         - rb_joint1
         - rb_joint2
         - rb_joint3
       command_interfaces:		#关节接受位置输入
         - position
         - velocity
         - torque
       state_interfaces:		#关节反馈位置和速度
         - position
         - velocity
         - torque